export const ACTIONS = {
  BROWSER: {
    SET_URL: 'SET_URL',
  },
  FAVORITES: {
    ADD_FAVORITE: 'ADD_FAVORITE',
  },
  LOADING: {
    SET_LOADING: 'SET_LOADING',
  },
  MODALS: {
    ADD_MODAL: 'ADD_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    CLEAR_LIST: 'CLEAR_LIST',
  },
  REQUESTS: {
    FETCH: 'FETCH',
    START_FETCH_POKEDEX: 'START_FETCH_POKEDEX',
    START_FETCH_DIGDEX: 'START_FETCH_DIGDEX',
  },
};
